# Generated by Django 3.1 on 2025-08-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='test_field',
            field=models.BooleanField(default=False),
        ),
    ]
