# Generated by Django 3.1 on 2025-08-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_reviewrating_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='test_field',
        ),
    ]
